name: Build Android APK (Nix Flake)

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Nix
        uses: cachix/install-nix-action@v25
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Build Android APK using flake
        run: nix run .#buildAndroid

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: neon-invaders-android-apk
          path: build-android/neon-invaders.apk
          if-no-files-found: error

      - name: Create GitHub Release with APK
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build-android/neon-invaders.apk
          generate_release_notes: true