name: Build Android APK (Nix Flake)

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-nix-config: |
            experimental-features = nix-command flakes

      - name: Setup dev shell
        uses: DetermineSystems/magic-nix-cache-action@v2
        with:
            source-run: true

      - name: Build Android APK using flake
        run: |
          nix develop --command build-android

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: neon-invaders-android-apk
          path: build-android/neon-invaders.apk
          if-no-files-found: error

      - name: Create GitHub Release with APK
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            build-android/neon-invaders.apk
          generate_release_notes: true