name: Build Android APK (Nix)

permissions:
  contents: write # needed to create GitHub Releases on tag builds

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  android-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Nix
        uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Setup Cachix
        uses: cachix/cachix-action@v12
        with:
          name: nixpkgs-wayland
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

      - name: Build Android APK
        run: |
          nix develop --command build-android

      - name: Upload APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: neon-invaders-android
          path: |
            android/love-android/app/build/outputs/apk/debug/*.apk
          if-no-files-found: error

      # On tag builds, also publish a Release with direct .apk assets
      - name: Create GitHub Release with APK(s)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: |
            android/love-android/app/build/outputs/apk/debug/*.apk
          generate_release_notes: true
