name: Build Android APK (love-actions)

on:
  push:
    branches: [ main, master ]
  pull_request:

jobs:
  love-android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build .love package
        shell: bash
        run: |
          zip -9 -r game.love . \
            -x "android/**" \
            -x ".git/**" \
            -x ".github/**" \
            -x "**/node_modules/**" \
            -x "**/build/**" \
            -x "**/dist/**"

      - name: Build love android
        id: build-love
        uses: love-actions/love-actions-android@v2
        with:
          app-name: "Neon Invaders"
          bundle-id: "org.love2d.android"
          resource-path: "android/icons"
          # icon-specifier: "@mipmap/ic_launcher"
          love-ref: "11.5"
          love-package: "game.love"
          product-name: "neon-invaders"
          version-string: "12.0"
          version-code: 33
          output-folder: "build"

      - name: Upload APK(s)
        uses: actions/upload-artifact@v4
        with:
          name: neon-invaders-android
          path: |
            build/*.apk
            build/**/*.apk
          if-no-files-found: error
